-- TasteTrainer migration 003 (2026-08-04). Run once in the Supabase SQL editor
-- (Curiosity project). Safe to re-run — every statement is idempotent.
--
-- One change: durable storage for each world's map (8-field-map.md).
--
-- Why a table rather than deriving it per request: the map is generated by a model,
-- and a model asked to lay out a world twice gives two different answers. A map that
-- rearranges itself between visits can never be learned, which defeats the entire
-- point of making it spatial. So the map is a stored artifact — generated once, then
-- amended by accepted suggestions and by dragging — not a query result.
--
-- One row per domain ('physical' | 'digital'), holding a WorldMap document
-- (shared/types.ts): the world's two axes, its named regions, where each dataset and
-- each proposed field sits, and any changes the last review proposed.

CREATE TABLE IF NOT EXISTS taste_world_maps (
  domain     text PRIMARY KEY,   -- 'physical' | 'digital'
  data       jsonb NOT NULL,     -- a WorldMap
  updated_at timestamptz DEFAULT now()
);

-- Privileges (needed when this is applied via the management API rather than the
-- dashboard SQL editor, matching the note in 001 and 002).
GRANT SELECT, INSERT, UPDATE, DELETE ON taste_world_maps TO service_role;
